spring.application.name=bytequanta
management.endpoints.web.exposure.include=*

logging.level.root=INFO
logging.level.org.example.bytequanta=DEBUG

logging.file.path= /logs/application.log

# Kafka bootstrap servers
spring.kafka.bootstrap-servers=localhost:9094
#create a topic
# kafka-topics.sh --create --topic test-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1

spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
